# Generated by Django 6.0 on 2025-12-21 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер цеха')),
                ('name', models.CharField(verbose_name='Название цеха')),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цеха',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер участка')),
                ('name', models.CharField(verbose_name='Название участка')),
                ('workshop', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sectors',
                    to='shift_report.workshop',
                    verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
    ]
