# Generated by Django 6.0 on 2026-01-16 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('code', models.CharField(help_text='Краткий код для идентификации (например: ORG, TECH)', max_length=50, unique=True, verbose_name='Код группы')),
                ('color', models.CharField(default='#6c757d', help_text='Цвет для визуализации в отчётах', max_length=7, verbose_name='Цвет (HEX)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Группа причин отклонений',
                'verbose_name_plural': 'Группы причин отклонений',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('unit', models.CharField(default='шт.', max_length=50, verbose_name='Единица измерения')),
                ('takt_time', models.PositiveIntegerField(blank=True, help_text='Интервал времени для производства одной единицы продукции', null=True, verbose_name='Время такта (норматив), сек')),
                ('cycle_time', models.PositiveIntegerField(blank=True, help_text='Фактическое время выполнения всех операций', null=True, verbose_name='Время цикла (факт), сек')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивная продукция не отображается в списках выбора', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер смены')),
                ('name', models.CharField(help_text='Например: Первая смена, Дневная, Ночная', max_length=100, verbose_name='Название смены')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('lunch_break', models.PositiveIntegerField(default=30, verbose_name='Обед, мин')),
                ('personal_break', models.PositiveIntegerField(default=10, verbose_name='Личные нужды, мин')),
                ('handover_break', models.PositiveIntegerField(default=10, verbose_name='Приём-передача смены, мин')),
                ('other_break', models.PositiveIntegerField(default=0, verbose_name='Прочие перерывы, мин')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='DeviationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название причины')),
                ('code', models.CharField(help_text='Краткий код для идентификации', max_length=50, unique=True, verbose_name='Код причины')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('description', models.TextField(blank=True, default='', help_text='Подробное описание или примеры', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False, help_text='Автоматически обновляется для расчёта топ-5 частых причин', verbose_name='Количество использований')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='shift_report.deviationgroup', verbose_name='Группа причин')),
            ],
            options={
                'verbose_name': 'Причина отклонения',
                'verbose_name_plural': 'Причины отклонений',
                'ordering': ['group__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер рабочего места')),
                ('name', models.CharField(max_length=255, verbose_name='Название рабочего места')),
                ('equipment_type', models.CharField(blank=True, default='', max_length=255, verbose_name='Тип оборудования')),
                ('passport_capacity', models.PositiveIntegerField(blank=True, help_text='Используется для бланков Типа 2 (по мощности РМ)', null=True, verbose_name='Паспортная мощность, шт/час')),
                ('achieved_capacity', models.PositiveIntegerField(blank=True, help_text='Статистическая мощность на основе фактических данных', null=True, verbose_name='Достигнутая мощность, шт/час')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='shift_report.sector', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
                'ordering': ['sector__workshop__number', 'sector__number', 'number'],
                'unique_together': {('sector', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('personnel_number', models.CharField(help_text='Уникальный табельный номер (6-8 цифр)', max_length=20, unique=True, verbose_name='Табельный номер')),
                ('pin_hash', models.CharField(help_text='Хранится в зашифрованном виде', max_length=128, verbose_name='PIN-код (хеш)')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('operator', 'Оператор'), ('master', 'Мастер'), ('chief', 'Начальник'), ('admin', 'Администратор')], default='operator', max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные сотрудники не могут войти в систему', verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Доступ к админке')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('sector', models.ForeignKey(blank=True, help_text='Для мастеров', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='shift_report.sector', verbose_name='Участок')),
                ('workshop', models.ForeignKey(blank=True, help_text='Для начальников цехов и администраторов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='shift_report.workshop', verbose_name='Цех')),
                ('workplace', models.ForeignKey(blank=True, help_text='Для операторов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='shift_report.workplace', verbose_name='Рабочее место')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
