# Generated by Django 6.0 on 2026-01-17 16:51

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_report', '0002_deviationgroup_product_shift_deviationreason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PABlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('blank_type', models.CharField(choices=[('type_1', 'Тип 1: По времени такта'), ('type_2', 'Тип 2: По мощности РМ'), ('type_3', 'Тип 3: Несколько номенклатур'), ('type_4', 'Тип 4: Менее 1 изделия в час'), ('type_5', 'Тип 5: Менее 1 изделия в смену')], default='type_1', max_length=20, verbose_name='Тип бланка')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('planned_quantity', models.PositiveIntegerField(help_text='Суточный/сменный план производства', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Плановый объём, шт')),
                ('takt_time', models.DecimalField(blank=True, decimal_places=2, help_text='Тт = Фонд времени смены / Плановый объём', max_digits=10, null=True, verbose_name='Время такта, сек')),
                ('production_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Темп = 3600 / Тт', max_digits=10, null=True, verbose_name='Темп производства, шт/час')),
                ('hourly_plan', models.PositiveIntegerField(blank=True, help_text='План на один час (округлённый темп)', null=True, verbose_name='Часовой план, шт')),
                ('workplace_capacity', models.PositiveIntegerField(blank=True, help_text='Используется для бланков Типа 2', null=True, verbose_name='Мощность РМ, шт/час')),
                ('total_plan', models.PositiveIntegerField(default=0, editable=False, verbose_name='Итого план, шт')),
                ('total_fact', models.PositiveIntegerField(default=0, editable=False, verbose_name='Итого факт, шт')),
                ('total_deviation', models.IntegerField(default=0, editable=False, help_text='Положительное = перевыполнение, отрицательное = недовыполнение', verbose_name='Итого отклонение, шт')),
                ('total_downtime', models.PositiveIntegerField(default=0, editable=False, verbose_name='Итого простой, мин')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=6, verbose_name='Процент выполнения, %')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blanks', to='shift_report.employee', verbose_name='Создал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa_blanks', to='shift_report.product', verbose_name='Продукция')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa_blanks', to='shift_report.shift', verbose_name='Смена')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa_blanks', to='shift_report.workplace', verbose_name='Рабочее место')),
            ],
            options={
                'verbose_name': 'Бланк ПА',
                'verbose_name_plural': 'Бланки ПА',
                'ordering': ['-date', '-shift__number', 'workplace__number'],
            },
        ),
        migrations.CreateModel(
            name='PARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Номер часа')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('planned_quantity', models.PositiveIntegerField(default=0, verbose_name='План, шт')),
                ('cumulative_plan', models.PositiveIntegerField(default=0, help_text='Сумма плана с начала смены', verbose_name='План накопительный, шт')),
                ('actual_quantity', models.PositiveIntegerField(default=0, verbose_name='Факт, шт')),
                ('cumulative_fact', models.PositiveIntegerField(default=0, help_text='Сумма факта с начала смены', verbose_name='Факт накопительный, шт')),
                ('deviation', models.IntegerField(default=0, help_text='Факт - План (может быть отрицательным)', verbose_name='Отклонение, шт')),
                ('cumulative_deviation', models.IntegerField(default=0, verbose_name='Отклонение накопительное, шт')),
                ('downtime_minutes', models.PositiveIntegerField(default=0, verbose_name='Простой, мин')),
                ('is_filled', models.BooleanField(default=False, help_text='Отмечается при внесении фактических данных', verbose_name='Заполнено')),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name='Время заполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='shift_report.pablank', verbose_name='Бланк ПА')),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_records', to='shift_report.employee', verbose_name='Заполнил')),
            ],
            options={
                'verbose_name': 'Запись ПА',
                'verbose_name_plural': 'Записи ПА',
                'ordering': ['blank', 'hour_number'],
            },
        ),
        migrations.CreateModel(
            name='DeviationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Время простоя по данной причине', verbose_name='Длительность, мин')),
                ('comment', models.TextField(blank=True, default='', help_text='Дополнительные пояснения к причине отклонения', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deviations', to='shift_report.employee', verbose_name='Создал')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviation_entries', to='shift_report.deviationreason', verbose_name='Причина отклонения')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_deviations', to='shift_report.employee', verbose_name='Ответственный за простой')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='shift_report.parecord', verbose_name='Запись ПА')),
            ],
            options={
                'verbose_name': 'Запись об отклонении',
                'verbose_name_plural': 'Записи об отклонениях',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PATemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "Стандартный план - Деталь А"', max_length=255, verbose_name='Название шаблона')),
                ('blank_type', models.CharField(choices=[('type_1', 'Тип 1: По времени такта'), ('type_2', 'Тип 2: По мощности РМ'), ('type_3', 'Тип 3: Несколько номенклатур'), ('type_4', 'Тип 4: Менее 1 изделия в час'), ('type_5', 'Тип 5: Менее 1 изделия в смену')], default='type_1', max_length=20, verbose_name='Тип бланка')),
                ('planned_quantity', models.PositiveIntegerField(help_text='Стандартный план производства', verbose_name='Плановый объём, шт')),
                ('monday', models.BooleanField(default=True, verbose_name='Понедельник')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Вторник')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Среда')),
                ('thursday', models.BooleanField(default=True, verbose_name='Четверг')),
                ('friday', models.BooleanField(default=True, verbose_name='Пятница')),
                ('saturday', models.BooleanField(default=False, verbose_name='Суббота')),
                ('sunday', models.BooleanField(default=False, verbose_name='Воскресенье')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to='shift_report.employee', verbose_name='Создал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa_templates', to='shift_report.product', verbose_name='Продукция')),
                ('shift', models.ForeignKey(blank=True, help_text='Если указана, шаблон применяется только для этой смены', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pa_templates', to='shift_report.shift', verbose_name='Смена')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa_templates', to='shift_report.workplace', verbose_name='Рабочее место')),
            ],
            options={
                'verbose_name': 'Шаблон бланка ПА',
                'verbose_name_plural': 'Шаблоны бланков ПА',
                'ordering': ['workplace', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TakenMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_type', models.CharField(choices=[('fixed', 'Устранено'), ('in_repair', 'В ремонте'), ('operator_replaced', 'Заменён оператор'), ('plan_adjusted', 'Скорректирован план'), ('escalated', 'Эскалировано'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Тип меры')),
                ('description', models.TextField(help_text='Подробное описание принятых действий', verbose_name='Описание меры')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Когда проблема была устранена', null=True, verbose_name='Время устранения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_measures', to='shift_report.employee', verbose_name='Принял меру')),
                ('deviation_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='shift_report.deviationentry', verbose_name='Отклонение')),
            ],
            options={
                'verbose_name': 'Принятая мера',
                'verbose_name_plural': 'Принятые меры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pablank',
            index=models.Index(fields=['workplace', 'date', 'shift'], name='shift_repor_workpla_2960d3_idx'),
        ),
        migrations.AddIndex(
            model_name='pablank',
            index=models.Index(fields=['date', 'status'], name='shift_repor_date_21455d_idx'),
        ),
        migrations.AddIndex(
            model_name='pablank',
            index=models.Index(fields=['created_by', 'date'], name='shift_repor_created_7e45a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='pablank',
            constraint=models.UniqueConstraint(fields=('workplace', 'date', 'shift'), name='unique_blank_per_workplace_date_shift'),
        ),
        migrations.AddIndex(
            model_name='parecord',
            index=models.Index(fields=['blank', 'hour_number'], name='shift_repor_blank_i_97188a_idx'),
        ),
        migrations.AddIndex(
            model_name='parecord',
            index=models.Index(fields=['is_filled'], name='shift_repor_is_fill_65cad8_idx'),
        ),
        migrations.AddConstraint(
            model_name='parecord',
            constraint=models.UniqueConstraint(fields=('blank', 'hour_number'), name='unique_record_per_blank_hour'),
        ),
        migrations.AddIndex(
            model_name='deviationentry',
            index=models.Index(fields=['record', 'reason'], name='shift_repor_record__73fbbd_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationentry',
            index=models.Index(fields=['reason'], name='shift_repor_reason__0152a7_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationentry',
            index=models.Index(fields=['created_at'], name='shift_repor_created_f8842f_idx'),
        ),
        migrations.AddIndex(
            model_name='patemplate',
            index=models.Index(fields=['workplace', 'is_active'], name='shift_repor_workpla_e2e44f_idx'),
        ),
        migrations.AddIndex(
            model_name='patemplate',
            index=models.Index(fields=['created_by'], name='shift_repor_created_8f4dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='takenmeasure',
            index=models.Index(fields=['deviation_entry'], name='shift_repor_deviati_a694ce_idx'),
        ),
        migrations.AddIndex(
            model_name='takenmeasure',
            index=models.Index(fields=['measure_type'], name='shift_repor_measure_320ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='takenmeasure',
            index=models.Index(fields=['created_at'], name='shift_repor_created_700635_idx'),
        ),
    ]
